 Network hfurlan-java_rinha-network  Creating
 Network hfurlan-java_rinha-network  Created
 Container hfurlan-java-db-1  Creating
 Container hfurlan-java-db-1  Created
 Container hfurlan-java-api02-1  Creating
 Container hfurlan-java-api01-1  Creating
 Container hfurlan-java-api02-1  Created
 Container hfurlan-java-api01-1  Created
 Container hfurlan-java-nginx-1  Creating
 Container hfurlan-java-nginx-1  Created
Attaching to api01-1, api02-1, db-1, nginx-1
db-1     | The files belonging to this database system will be owned by user "postgres".
db-1     | This user must also own the server process.
db-1     | 
db-1     | The database cluster will be initialized with locale "en_US.utf8".
db-1     | The default database encoding has accordingly been set to "UTF8".
db-1     | The default text search configuration will be set to "english".
db-1     | 
db-1     | Data page checksums are disabled.
db-1     | 
db-1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db-1     | creating subdirectories ... ok
db-1     | selecting dynamic shared memory implementation ... posix
db-1     | selecting default max_connections ... 100
db-1     | selecting default shared_buffers ... 128MB
db-1     | selecting default time zone ... Etc/UTC
db-1     | creating configuration files ... ok
db-1     | running bootstrap script ... ok
api02-1  | Conectando no BD...
api02-1  | DB_HOSTNAME:db
api02-1  | DB_NAME:rinha
api02-1  | DB_USERNAME:admin
api02-1  | DB_MAX_CONNECTIONS:5
api02-1  | VERSAO:0.0.1-SNAPSHOT
api01-1  | Conectando no BD...
api01-1  | DB_HOSTNAME:db
api01-1  | DB_NAME:rinha
api01-1  | DB_USERNAME:admin
api01-1  | DB_MAX_CONNECTIONS:5
api01-1  | VERSAO:0.0.1-SNAPSHOT
api02-1  | Exception in thread "main" org.postgresql.util.PSQLException: Connection to db:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
api02-1  | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:346)
api02-1  | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
api02-1  | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:273)
api02-1  | 	at org.postgresql.Driver.makeConnection(Driver.java:446)
api02-1  | 	at org.postgresql.Driver.connect(Driver.java:298)
api02-1  | 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
api02-1  | 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
api02-1  | 	at com.github.hfurlan.rinha.App.<init>(App.java:63)
api02-1  | 	at com.github.hfurlan.rinha.App.main(App.java:320)
api02-1  | Caused by: java.net.ConnectException: Connection refused
api02-1  | 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
api02-1  | 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)
api02-1  | 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
api02-1  | 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
api02-1  | 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
api02-1  | 	at java.base/java.net.Socket.connect(Socket.java:751)
api02-1  | 	at org.postgresql.core.PGStream.createSocket(PGStream.java:243)
api02-1  | 	at org.postgresql.core.PGStream.<init>(PGStream.java:98)
api02-1  | 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:136)
api02-1  | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:262)
api02-1  | 	... 8 more
api01-1  | Exception in thread "main" org.postgresql.util.PSQLException: Connection to db:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
api01-1  | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:346)
api01-1  | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
api01-1  | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:273)
api01-1  | 	at org.postgresql.Driver.makeConnection(Driver.java:446)
api01-1  | 	at org.postgresql.Driver.connect(Driver.java:298)
api01-1  | 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
api01-1  | 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
api01-1  | 	at com.github.hfurlan.rinha.App.<init>(App.java:63)
api01-1  | 	at com.github.hfurlan.rinha.App.main(App.java:320)
api01-1  | Caused by: java.net.ConnectException: Connection refused
api01-1  | 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
api01-1  | 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)
api01-1  | 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
api01-1  | 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
api01-1  | 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
api01-1  | 	at java.base/java.net.Socket.connect(Socket.java:751)
api01-1  | 	at org.postgresql.core.PGStream.createSocket(PGStream.java:243)
api01-1  | 	at org.postgresql.core.PGStream.<init>(PGStream.java:98)
api01-1  | 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:136)
api01-1  | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:262)
api01-1  | 	... 8 more
nginx-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
nginx-1  | 2024/03/05 14:12:01 [emerg] 1#1: host not found in upstream "api01:8081" in /etc/nginx/nginx.conf:11
nginx-1  | nginx: [emerg] host not found in upstream "api01:8081" in /etc/nginx/nginx.conf:11
db-1     | performing post-bootstrap initialization ... ok
db-1     | syncing data to disk ... ok
db-1     | 
db-1     | 
db-1     | Success. You can now start the database server using:
db-1     | 
db-1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db-1     | 
db-1     | initdb: warning: enabling "trust" authentication for local connections
db-1     | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
api02-1 exited with code 0
db-1     | waiting for server to start....2024-03-05 14:12:03.201 UTC [48] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-03-05 14:12:03.211 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-03-05 14:12:03.225 UTC [51] LOG:  database system was shut down at 2024-03-05 14:12:01 UTC
db-1     | 2024-03-05 14:12:03.239 UTC [48] LOG:  database system is ready to accept connections
db-1     |  done
db-1     | server started
api01-1 exited with code 0
nginx-1 exited with code 0
db-1     | CREATE DATABASE
db-1     | 
db-1     | 
db-1     | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/ddl.sql
db-1     | CREATE TABLE
db-1     | CREATE TABLE
db-1     | CREATE TABLE
db-1     | CREATE FUNCTION
db-1     | CREATE FUNCTION
db-1     | CREATE TRIGGER
db-1     | CREATE TRIGGER
db-1     | CREATE FUNCTION
db-1     | CREATE FUNCTION
db-1     | 
db-1     | 
db-1     | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/dml.sql
db-1     | INSERT 0 5
db-1     | 
db-1     | 
db-1     | waiting for server to shut down...2024-03-05 14:12:03.624 UTC [48] LOG:  received fast shutdown request
db-1     | .2024-03-05 14:12:03.638 UTC [48] LOG:  aborting any active transactions
db-1     | 2024-03-05 14:12:03.641 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
db-1     | 2024-03-05 14:12:03.641 UTC [49] LOG:  shutting down
db-1     | 2024-03-05 14:12:03.653 UTC [49] LOG:  checkpoint starting: shutdown immediate
db-1     | .2024-03-05 14:12:05.397 UTC [49] LOG:  checkpoint complete: wrote 939 buffers (5.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.790 s, sync=0.551 s, total=1.756 s; sync files=308, longest=0.222 s, average=0.002 s; distance=4306 kB, estimate=4306 kB; lsn=0/191F2E0, redo lsn=0/191F2E0
db-1     | 2024-03-05 14:12:05.402 UTC [48] LOG:  database system is shut down
db-1     |  done
db-1     | server stopped
db-1     | 
db-1     | PostgreSQL init process complete; ready for start up.
db-1     | 
db-1     | 2024-03-05 14:12:05.472 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-03-05 14:12:05.472 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1     | 2024-03-05 14:12:05.472 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1     | 2024-03-05 14:12:05.498 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-03-05 14:12:05.509 UTC [68] LOG:  database system was shut down at 2024-03-05 14:12:05 UTC
db-1     | 2024-03-05 14:12:05.516 UTC [1] LOG:  database system is ready to accept connections
api02-1  | Conectando no BD...
api02-1  | DB_HOSTNAME:db
api02-1  | DB_NAME:rinha
api02-1  | DB_USERNAME:admin
api02-1  | DB_MAX_CONNECTIONS:5
api02-1  | VERSAO:0.0.1-SNAPSHOT
api02-1 exited with code 0
api01-1 exited with code 0
api01-1  | Conectando no BD...
api01-1  | Conectando no BD...
api01-1  | DB_HOSTNAME:db
api01-1  | DB_HOSTNAME:db
api01-1  | DB_NAME:rinha
api01-1  | DB_USERNAME:admin
api01-1  | DB_NAME:rinha
api01-1  | DB_USERNAME:admin
api01-1  | DB_MAX_CONNECTIONS:5
api01-1  | DB_MAX_CONNECTIONS:5
api01-1  | VERSAO:0.0.1-SNAPSHOT
api01-1  | VERSAO:0.0.1-SNAPSHOT
api02-1  | Servidor iniciado e aguardando conexoes na PORTA 8082 (5 threads)
api02-1  | Servidor iniciado e aguardando conexoes na PORTA 8082 (5 threads)
api01-1  | Servidor iniciado e aguardando conexoes na PORTA 8081 (5 threads)
api01-1  | Servidor iniciado e aguardando conexoes na PORTA 8081 (5 threads)
nginx-1  | 2024/03/05 14:12:07 [error] 22#22: *4 no live upstreams while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/05 14:12:09 [error] 22#22: *5 no live upstreams while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/05 14:12:11 [error] 22#22: *6 no live upstreams while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/05 14:12:13 [error] 22#22: *7 no live upstreams while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
db-1     | 2024-03-05 14:12:38.373 UTC [81] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:38.653 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:39.386 UTC [74] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:39.494 UTC [77] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:39.529 UTC [72] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:39.637 UTC [74] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:39.707 UTC [77] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:39.814 UTC [73] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:41.139 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:41.301 UTC [81] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:41.687 UTC [72] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:42.174 UTC [80] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:42.261 UTC [77] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:42.565 UTC [74] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:42.808 UTC [76] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:43.081 UTC [81] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:43.110 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:43.172 UTC [76] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:43.257 UTC [81] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:43.371 UTC [79] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:43.686 UTC [74] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:43.715 UTC [76] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:43.771 UTC [78] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:43.915 UTC [76] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:44.874 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:44.901 UTC [80] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:44.928 UTC [73] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:44.982 UTC [77] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:45.063 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:45.090 UTC [74] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:45.223 UTC [80] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:45.619 UTC [73] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:45.802 UTC [79] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:46.421 UTC [74] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:46.446 UTC [76] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:46.496 UTC [78] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:46.521 UTC [81] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:46.596 UTC [76] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:46.721 UTC [80] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:46.746 UTC [73] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:46.821 UTC [72] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:47.046 UTC [74] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:47.071 UTC [76] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:47.146 UTC [72] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:47.266 UTC [78] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:47.313 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:47.671 UTC [76] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:47.694 UTC [79] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:48.052 UTC [72] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:48.075 UTC [80] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:48.172 UTC [79] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:48.284 UTC [74] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:48.375 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:48.398 UTC [76] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:48.648 UTC [80] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:48.784 UTC [72] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:48.807 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:48.876 UTC [79] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:48.990 UTC [73] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:49.081 UTC [80] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:49.235 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:49.257 UTC [81] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:49.649 UTC [80] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:49.757 UTC [78] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:49.780 UTC [72] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:49.802 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:49.823 UTC [81] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:50.341 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:50.405 UTC [74] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:50.597 UTC [80] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:50.682 UTC [79] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:50.724 UTC [77] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:50.766 UTC [81] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:50.958 UTC [72] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:50.979 UTC [77] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:51.044 UTC [76] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:51.064 UTC [74] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:51.107 UTC [78] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:51.128 UTC [77] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:51.171 UTC [76] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:51.211 UTC [72] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:51.232 UTC [78] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:51.271 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:51.391 UTC [80] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:51.771 UTC [80] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:51.872 UTC [78] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:51.911 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:51.931 UTC [76] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:52.131 UTC [78] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:52.190 UTC [76] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:52.406 UTC [80] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:52.425 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:52.445 UTC [76] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:52.504 UTC [72] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:52.523 UTC [80] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:52.602 UTC [79] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:52.642 UTC [77] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:52.778 UTC [77] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:52.818 UTC [81] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:53.033 UTC [80] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:53.207 UTC [73] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:53.265 UTC [77] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:53.566 UTC [73] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:53.586 UTC [74] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:53.661 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:53.774 UTC [81] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:54.038 UTC [80] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:54.132 UTC [81] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:54.189 UTC [74] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:54.207 UTC [72] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:54.334 UTC [72] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:54.389 UTC [73] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:54.426 UTC [74] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:54.461 UTC [78] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:54.480 UTC [77] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:54.498 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:54.643 UTC [80] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:54.916 UTC [72] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:54.989 UTC [76] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:55.043 UTC [78] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:55.331 UTC [76] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:55.492 UTC [78] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:55.546 UTC [73] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:55.653 UTC [73] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:56.028 UTC [74] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:56.153 UTC [79] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:56.171 UTC [77] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:56.204 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:56.425 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:56.527 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:56.594 UTC [77] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:56.764 UTC [73] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:56.798 UTC [74] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:56.967 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:57.018 UTC [79] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:57.221 UTC [74] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:57.254 UTC [78] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:57.287 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:57.404 UTC [73] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:57.537 UTC [74] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:57.554 UTC [79] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:57.587 UTC [72] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:57.754 UTC [80] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:57.771 UTC [79] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:57.854 UTC [80] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:57.887 UTC [77] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:57.954 UTC [76] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:57.971 UTC [74] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:57.987 UTC [79] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:58.004 UTC [78] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:58.037 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:58.104 UTC [77] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:58.121 UTC [78] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:58.137 UTC [81] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:58.188 UTC [74] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:58.236 UTC [81] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:58.284 UTC [80] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:58.365 UTC [73] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:58.462 UTC [73] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:58.479 UTC [76] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:58.559 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:58.802 UTC [74] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:58.881 UTC [73] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:58.962 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:59.091 UTC [76] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:59.389 UTC [76] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:59.421 UTC [79] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:59.436 UTC [77] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:59.514 UTC [79] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:59.577 UTC [73] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:59.655 UTC [72] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:59.718 UTC [74] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:59.780 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:59.827 UTC [79] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:59.843 UTC [78] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:59.874 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:59.889 UTC [76] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:59.905 UTC [80] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:59.921 UTC [79] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:12:59.937 UTC [77] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:00.014 UTC [74] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:00.186 UTC [73] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:00.292 UTC [76] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:00.308 UTC [80] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:00.475 UTC [73] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:00.504 UTC [74] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:00.535 UTC [78] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:00.549 UTC [72] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:00.610 UTC [74] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:00.837 UTC [72] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:00.852 UTC [81] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:00.928 UTC [72] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:01.035 UTC [72] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:01.049 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:01.081 UTC [80] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:01.126 UTC [78] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:01.141 UTC [81] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:01.156 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:01.172 UTC [80] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:01.184 UTC [74] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:01.259 UTC [73] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:01.288 UTC [74] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:01.332 UTC [81] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:01.347 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:01.376 UTC [80] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:01.465 UTC [80] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:01.568 UTC [74] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:01.612 UTC [72] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:01.641 UTC [73] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:01.744 UTC [80] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:01.773 UTC [77] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:01.980 UTC [72] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:02.038 UTC [74] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:02.068 UTC [78] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:02.141 UTC [74] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:02.172 UTC [81] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:02.214 UTC [80] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:02.330 UTC [79] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:02.373 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:02.417 UTC [74] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:02.576 UTC [76] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:02.678 UTC [80] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:02.691 UTC [79] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:02.707 UTC [77] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:02.721 UTC [72] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:02.866 UTC [80] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:03.026 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:03.069 UTC [79] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:03.098 UTC [72] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:03.156 UTC [74] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:03.171 UTC [79] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:03.184 UTC [72] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:03.199 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:03.241 UTC [74] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:03.268 UTC [78] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:03.283 UTC [81] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:03.325 UTC [80] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:03.466 UTC [81] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:03.537 UTC [78] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:03.634 UTC [78] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:03.678 UTC [80] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:03.719 UTC [78] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:03.761 UTC [76] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:03.831 UTC [81] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:03.930 UTC [73] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:03.945 UTC [76] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:03.987 UTC [78] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:04.001 UTC [72] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:04.044 UTC [80] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:04.086 UTC [78] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:04.128 UTC [76] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:04.198 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:04.225 UTC [80] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:04.237 UTC [79] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:04.279 UTC [81] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:04.292 UTC [73] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:04.333 UTC [79] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:04.372 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:04.387 UTC [73] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:04.481 UTC [80] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:04.508 UTC [72] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:04.522 UTC [78] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:04.738 UTC [76] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:04.752 UTC [74] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:04.873 UTC [78] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:04.900 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:04.914 UTC [76] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:04.927 UTC [74] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:04.941 UTC [72] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:04.981 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:05.022 UTC [79] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:05.157 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:05.171 UTC [73] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:05.198 UTC [72] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:05.211 UTC [78] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:05.238 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:05.251 UTC [76] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:05.292 UTC [72] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:05.426 UTC [76] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:05.454 UTC [79] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:05.468 UTC [78] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:05.522 UTC [73] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:05.535 UTC [74] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:06.049 UTC [74] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:06.062 UTC [79] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:06.130 UTC [73] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:06.209 UTC [73] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:06.235 UTC [72] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:06.248 UTC [77] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:06.274 UTC [80] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:06.313 UTC [79] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:06.339 UTC [77] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:06.417 UTC [81] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:06.508 UTC [78] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:06.560 UTC [79] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:06.651 UTC [79] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:06.729 UTC [79] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:06.768 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:06.963 UTC [73] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:07.054 UTC [74] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:07.119 UTC [80] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:07.195 UTC [80] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:07.258 UTC [78] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:07.271 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:07.347 UTC [78] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:07.359 UTC [80] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:07.372 UTC [76] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:07.385 UTC [74] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:07.435 UTC [80] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:07.537 UTC [73] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:07.664 UTC [77] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:07.676 UTC [75] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:07.739 UTC [77] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:07.752 UTC [78] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:07.777 UTC [76] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:07.802 UTC [79] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:07.815 UTC [81] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:07.891 UTC [72] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:07.904 UTC [81] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:07.992 UTC [78] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
db-1     | 2024-03-05 14:13:08.030 UTC [73] ERROR:  new row for relation "saldos" violates check constraint "saldo_valido"
