 Network rinha-nginx-2024q1  Creating
 Network rinha-nginx-2024q1  Created
 Container mysql  Creating
 Container mysql  Created
 Container kleytonsolinho-golang-api02-1  Creating
 Container kleytonsolinho-golang-api01-1  Creating
 Container kleytonsolinho-golang-api01-1  Created
 Container kleytonsolinho-golang-api02-1  Created
 Container nginx  Creating
 Container nginx  Created
Attaching to api01-1, api02-1, mysql, nginx
mysql    | 2024-03-07 14:54:40+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.44-1.el7 started.
mysql    | 2024-03-07 14:54:40+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql    | 2024-03-07 14:54:40+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.44-1.el7 started.
mysql    | 2024-03-07 14:54:40+00:00 [Warn] [Entrypoint]: MYSQL_PASSWORD specified, but missing MYSQL_USER; MYSQL_PASSWORD will be ignored
mysql    | 2024-03-07 14:54:40+00:00 [Note] [Entrypoint]: Initializing database files
mysql    | 2024-03-07T14:54:40.316217Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
api01-1  | 2024/03/07 14:54:40 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | 
api01-1  | goroutine 1 [running]:
api01-1  | main.main()
api01-1  | 	/app/cmd/server/main.go:16 +0x47f
api02-1  | 2024/03/07 14:54:40 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | 
api02-1  | goroutine 1 [running]:
api02-1  | main.main()
api02-1  | 	/app/cmd/server/main.go:16 +0x47f
mysql    | 2024-03-07T14:54:41.043751Z 0 [Warning] InnoDB: New log files created, LSN=45790
mysql    | 2024-03-07T14:54:41.124096Z 0 [Warning] InnoDB: Creating foreign key constraint system tables.
mysql    | 2024-03-07T14:54:41.159869Z 0 [Warning] No existing UUID has been found, so we assume that this is the first time that this server has been started. Generating a new UUID: a086f31b-dc92-11ee-aa52-0242c0a80002.
mysql    | 2024-03-07T14:54:41.163916Z 0 [Warning] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
mysql    | 2024-03-07T14:54:41.258739Z 0 [Warning] A deprecated TLS version TLSv1 is enabled. Please use TLSv1.2 or higher.
mysql    | 2024-03-07T14:54:41.258754Z 0 [Warning] A deprecated TLS version TLSv1.1 is enabled. Please use TLSv1.2 or higher.
mysql    | 2024-03-07T14:54:41.259203Z 0 [Warning] CA certificate ca.pem is self signed.
mysql    | 2024-03-07T14:54:41.291308Z 1 [Warning] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
nginx    | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx    | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx    | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx    | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx    | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx    | /docker-entrypoint.sh: Configuration complete; ready for start up
nginx    | 2024/03/07 14:54:42 [emerg] 1#1: host not found in upstream "api02:8080" in /etc/nginx/nginx.conf:12
nginx    | nginx: [emerg] host not found in upstream "api02:8080" in /etc/nginx/nginx.conf:12
api01-1 exited with code 0
api02-1 exited with code 0
nginx exited with code 1
api02-1  | 2024/03/07 14:54:40 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | 
api02-1  | goroutine 1 [running]:
api02-1  | main.main()
api02-1  | 	/app/cmd/server/main.go:16 +0x47f
api02-1  | 2024/03/07 14:54:42 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | 
api02-1  | goroutine 1 [running]:
api02-1  | main.main()
api02-1  | 	/app/cmd/server/main.go:16 +0x47f
api02-1  | 2024/03/07 14:54:44 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | 
api02-1  | goroutine 1 [running]:
api02-1  | main.main()
api02-1  | 	/app/cmd/server/main.go:16 +0x47f
api02-1  | 2024/03/07 14:54:45 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | 
api02-1  | goroutine 1 [running]:
api02-1  | main.main()
api02-1  | 	/app/cmd/server/main.go:16 +0x47f
api01-1 exited with code 0
api02-1 exited with code 0
api01-1  | 2024/03/07 14:54:40 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | 
api01-1  | goroutine 1 [running]:
api01-1  | main.main()
api01-1  | 	/app/cmd/server/main.go:16 +0x47f
api01-1  | 2024/03/07 14:54:42 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | 
api01-1  | goroutine 1 [running]:
api01-1  | main.main()
api01-1  | 	/app/cmd/server/main.go:16 +0x47f
api01-1  | 2024/03/07 14:54:43 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | 
api01-1  | goroutine 1 [running]:
api01-1  | main.main()
api01-1  | 	/app/cmd/server/main.go:16 +0x47f
api01-1  | 2024/03/07 14:54:45 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | 
api01-1  | goroutine 1 [running]:
api01-1  | main.main()
api01-1  | 	/app/cmd/server/main.go:16 +0x47f
api01-1  | 2024/03/07 14:54:46 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | 
api01-1  | goroutine 1 [running]:
api01-1  | main.main()
api01-1  | 	/app/cmd/server/main.go:16 +0x47f
api02-1  | 2024/03/07 14:54:40 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | 
api02-1  | goroutine 1 [running]:
api02-1  | main.main()
api02-1  | 	/app/cmd/server/main.go:16 +0x47f
api02-1  | 2024/03/07 14:54:42 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | 
api02-1  | goroutine 1 [running]:
api02-1  | main.main()
api02-1  | 	/app/cmd/server/main.go:16 +0x47f
api02-1  | 2024/03/07 14:54:44 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | 
api02-1  | goroutine 1 [running]:
api02-1  | main.main()
api02-1  | 	/app/cmd/server/main.go:16 +0x47f
api02-1  | 2024/03/07 14:54:45 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | 
api02-1  | goroutine 1 [running]:
api02-1  | main.main()
api02-1  | 	/app/cmd/server/main.go:16 +0x47f
api02-1  | 2024/03/07 14:54:46 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | 
api02-1  | goroutine 1 [running]:
api02-1  | main.main()
api02-1  | 	/app/cmd/server/main.go:16 +0x47f
api01-1 exited with code 2
api02-1 exited with code 2
api01-1  | 2024/03/07 14:54:40 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | 
api01-1  | goroutine 1 [running]:
api01-1  | main.main()
api01-1  | 	/app/cmd/server/main.go:16 +0x47f
api01-1  | 2024/03/07 14:54:42 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | 
api01-1  | goroutine 1 [running]:
api01-1  | main.main()
api01-1  | 	/app/cmd/server/main.go:16 +0x47f
api01-1  | 2024/03/07 14:54:43 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | 
api01-1  | goroutine 1 [running]:
api01-1  | main.main()
api01-1  | 	/app/cmd/server/main.go:16 +0x47f
api01-1  | 2024/03/07 14:54:45 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | 
api01-1  | goroutine 1 [running]:
api01-1  | main.main()
api01-1  | 	/app/cmd/server/main.go:16 +0x47f
api01-1  | 2024/03/07 14:54:46 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | 
api01-1  | goroutine 1 [running]:
api01-1  | main.main()
api01-1  | 	/app/cmd/server/main.go:16 +0x47f
api02-1  | 2024/03/07 14:54:40 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | 
api02-1  | goroutine 1 [running]:
api02-1  | main.main()
api02-1  | 	/app/cmd/server/main.go:16 +0x47f
api02-1  | 2024/03/07 14:54:42 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | 
api02-1  | goroutine 1 [running]:
api02-1  | main.main()
api02-1  | 	/app/cmd/server/main.go:16 +0x47f
api02-1  | 2024/03/07 14:54:44 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | 
api02-1  | goroutine 1 [running]:
api02-1  | main.main()
api02-1  | 	/app/cmd/server/main.go:16 +0x47f
api02-1  | 2024/03/07 14:54:45 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | 
api02-1  | goroutine 1 [running]:
api02-1  | main.main()
api02-1  | 	/app/cmd/server/main.go:16 +0x47f
api02-1  | 2024/03/07 14:54:46 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | 
api02-1  | goroutine 1 [running]:
api02-1  | main.main()
api02-1  | 	/app/cmd/server/main.go:16 +0x47f
api01-1 exited with code 2
api02-1 exited with code 2
api01-1  | 2024/03/07 14:54:40 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | 
api01-1  | goroutine 1 [running]:
api01-1  | main.main()
api01-1  | 	/app/cmd/server/main.go:16 +0x47f
api01-1  | 2024/03/07 14:54:42 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | 
api01-1  | goroutine 1 [running]:
api01-1  | main.main()
api01-1  | 	/app/cmd/server/main.go:16 +0x47f
api01-1  | 2024/03/07 14:54:43 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | 
api01-1  | goroutine 1 [running]:
api01-1  | main.main()
api01-1  | 	/app/cmd/server/main.go:16 +0x47f
api01-1  | 2024/03/07 14:54:45 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | 
api01-1  | goroutine 1 [running]:
api01-1  | main.main()
api01-1  | 	/app/cmd/server/main.go:16 +0x47f
api01-1  | 2024/03/07 14:54:46 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | 
api01-1  | goroutine 1 [running]:
api01-1  | main.main()
api01-1  | 	/app/cmd/server/main.go:16 +0x47f
api02-1  | 2024/03/07 14:54:40 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | 
api02-1  | goroutine 1 [running]:
api02-1  | main.main()
api02-1  | 	/app/cmd/server/main.go:16 +0x47f
api02-1  | 2024/03/07 14:54:42 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | 
api02-1  | goroutine 1 [running]:
api02-1  | main.main()
api02-1  | 	/app/cmd/server/main.go:16 +0x47f
api02-1  | 2024/03/07 14:54:44 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | 
api02-1  | goroutine 1 [running]:
api02-1  | main.main()
api02-1  | 	/app/cmd/server/main.go:16 +0x47f
api02-1  | 2024/03/07 14:54:45 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | 
api02-1  | goroutine 1 [running]:
api02-1  | main.main()
api02-1  | 	/app/cmd/server/main.go:16 +0x47f
api02-1  | 2024/03/07 14:54:46 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | 
api02-1  | goroutine 1 [running]:
api02-1  | main.main()
api02-1  | 	/app/cmd/server/main.go:16 +0x47f
api01-1 exited with code 2
api02-1 exited with code 2
api01-1  | 2024/03/07 14:54:40 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | 
api01-1  | goroutine 1 [running]:
api01-1  | main.main()
api01-1  | 	/app/cmd/server/main.go:16 +0x47f
api01-1  | 2024/03/07 14:54:42 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | 
api01-1  | goroutine 1 [running]:
api01-1  | main.main()
api01-1  | 	/app/cmd/server/main.go:16 +0x47f
api01-1  | 2024/03/07 14:54:43 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | 
api01-1  | goroutine 1 [running]:
api01-1  | main.main()
api01-1  | 	/app/cmd/server/main.go:16 +0x47f
api01-1  | 2024/03/07 14:54:45 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | 
api01-1  | goroutine 1 [running]:
api01-1  | main.main()
api01-1  | 	/app/cmd/server/main.go:16 +0x47f
api01-1  | 2024/03/07 14:54:46 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | 
api01-1  | goroutine 1 [running]:
api01-1  | main.main()
api01-1  | 	/app/cmd/server/main.go:16 +0x47f
api01-1  | 2024/03/07 14:54:48 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api01-1  | 
api01-1  | goroutine 1 [running]:
api01-1  | main.main()
api01-1  | 	/app/cmd/server/main.go:16 +0x47f
mysql    | 2024-03-07 14:54:49+00:00 [Note] [Entrypoint]: Database files initialized
mysql    | 2024-03-07 14:54:49+00:00 [Note] [Entrypoint]: Starting temporary server
mysql    | 2024-03-07 14:54:49+00:00 [Note] [Entrypoint]: Waiting for server startup
api02-1  | 2024/03/07 14:54:40 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | 
api02-1  | goroutine 1 [running]:
api02-1  | main.main()
api02-1  | 	/app/cmd/server/main.go:16 +0x47f
api02-1  | 2024/03/07 14:54:42 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | 
api02-1  | goroutine 1 [running]:
api02-1  | main.main()
api02-1  | 	/app/cmd/server/main.go:16 +0x47f
api02-1  | 2024/03/07 14:54:44 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | 
api02-1  | goroutine 1 [running]:
api02-1  | main.main()
api02-1  | 	/app/cmd/server/main.go:16 +0x47f
api02-1  | 2024/03/07 14:54:45 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | 
api02-1  | goroutine 1 [running]:
api02-1  | main.main()
api02-1  | 	/app/cmd/server/main.go:16 +0x47f
api02-1  | 2024/03/07 14:54:46 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | 
api02-1  | goroutine 1 [running]:
api02-1  | main.main()
api02-1  | 	/app/cmd/server/main.go:16 +0x47f
api02-1  | 2024/03/07 14:54:48 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | 
api02-1  | goroutine 1 [running]:
api02-1  | main.main()
api02-1  | 	/app/cmd/server/main.go:16 +0x47f
api01-1 exited with code 2
api02-1 exited with code 2
mysql    | 2024-03-07T14:54:49.670691Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
mysql    | 2024-03-07T14:54:49.671645Z 0 [Note] mysqld (mysqld 5.7.44) starting as process 126 ...
mysql    | 2024-03-07T14:54:49.673975Z 0 [Note] InnoDB: PUNCH HOLE support available
mysql    | 2024-03-07T14:54:49.673993Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mysql    | 2024-03-07T14:54:49.673997Z 0 [Note] InnoDB: Uses event mutexes
mysql    | 2024-03-07T14:54:49.674001Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
mysql    | 2024-03-07T14:54:49.674004Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.13
mysql    | 2024-03-07T14:54:49.674007Z 0 [Note] InnoDB: Using Linux native AIO
mysql    | 2024-03-07T14:54:49.674239Z 0 [Note] InnoDB: Number of pools: 1
mysql    | 2024-03-07T14:54:49.674356Z 0 [Note] InnoDB: Using CPU crc32 instructions
mysql    | 2024-03-07T14:54:49.675476Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
mysql    | 2024-03-07T14:54:49.680558Z 0 [Note] InnoDB: Completed initialization of buffer pool
mysql    | 2024-03-07T14:54:49.682065Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mysql    | 2024-03-07T14:54:49.693758Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
mysql    | 2024-03-07T14:54:49.701634Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mysql    | 2024-03-07T14:54:49.701675Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mysql    | 2024-03-07T14:54:49.732293Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mysql    | 2024-03-07T14:54:49.732898Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
mysql    | 2024-03-07T14:54:49.732909Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
mysql    | 2024-03-07T14:54:49.733845Z 0 [Note] InnoDB: 5.7.44 started; log sequence number 2768732
mysql    | 2024-03-07T14:54:49.734347Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mysql    | 2024-03-07T14:54:49.734594Z 0 [Note] Plugin 'FEDERATED' is disabled.
mysql    | 2024-03-07T14:54:49.735734Z 0 [Note] InnoDB: Buffer pool(s) load completed at 240307 14:54:49
mysql    | 2024-03-07T14:54:49.738474Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
mysql    | 2024-03-07T14:54:49.738486Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
mysql    | 2024-03-07T14:54:49.738489Z 0 [Warning] A deprecated TLS version TLSv1 is enabled. Please use TLSv1.2 or higher.
mysql    | 2024-03-07T14:54:49.738490Z 0 [Warning] A deprecated TLS version TLSv1.1 is enabled. Please use TLSv1.2 or higher.
mysql    | 2024-03-07T14:54:49.738929Z 0 [Warning] CA certificate ca.pem is self signed.
mysql    | 2024-03-07T14:54:49.738956Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
mysql    | 2024-03-07T14:54:49.747723Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
mysql    | 2024-03-07T14:54:49.752276Z 0 [Note] Event Scheduler: Loaded 0 events
mysql    | 2024-03-07T14:54:49.752492Z 0 [Note] mysqld: ready for connections.
mysql    | Version: '5.7.44'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server (GPL)
mysql    | 2024-03-07 14:54:50+00:00 [Note] [Entrypoint]: Temporary server started.
mysql    | '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
mysql    | 2024-03-07T14:54:50.543343Z 3 [Note] InnoDB: Stopping purge
mysql    | 2024-03-07T14:54:50.550398Z 3 [Note] InnoDB: Resuming purge
mysql    | 2024-03-07T14:54:50.553463Z 3 [Note] InnoDB: Stopping purge
mysql    | 2024-03-07T14:54:50.561587Z 3 [Note] InnoDB: Resuming purge
mysql    | 2024-03-07T14:54:50.564297Z 3 [Note] InnoDB: Stopping purge
mysql    | 2024-03-07T14:54:50.571634Z 3 [Note] InnoDB: Resuming purge
mysql    | 2024-03-07T14:54:50.574959Z 3 [Note] InnoDB: Stopping purge
mysql    | 2024-03-07T14:54:50.582024Z 3 [Note] InnoDB: Resuming purge
mysql    | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
mysql    | Warning: Unable to load '/usr/share/zoneinfo/leapseconds' as time zone. Skipping it.
mysql    | Warning: Unable to load '/usr/share/zoneinfo/tzdata.zi' as time zone. Skipping it.
mysql    | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
mysql    | Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.
mysql    | 2024-03-07 14:54:52+00:00 [Note] [Entrypoint]: Creating database mysql-db
mysql    | 
mysql    | 2024-03-07 14:54:52+00:00 [Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/script.sql
mysql    | ERROR 1064 (42000) at line 23: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INSERT INTO clientes (nome, limite, saldo)
mysql    |   VALUES
mysql    |     ('o barato sai caro', 10' at line 3
api01-1  | panic: dial tcp: lookup mysql on 127.0.0.11:53: server misbehaving
api01-1  | 
api01-1  | goroutine 1 [running]:
api01-1  | main.main()
api01-1  | 	/app/cmd/server/main.go:16 +0x47f
api02-1  | 2024/03/07 14:54:40 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | 
api02-1  | goroutine 1 [running]:
api02-1  | main.main()
api02-1  | 	/app/cmd/server/main.go:16 +0x47f
api02-1  | 2024/03/07 14:54:42 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | 
api02-1  | goroutine 1 [running]:
api02-1  | main.main()
api02-1  | 	/app/cmd/server/main.go:16 +0x47f
api02-1  | 2024/03/07 14:54:44 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | 
api02-1  | goroutine 1 [running]:
api02-1  | main.main()
api02-1  | 	/app/cmd/server/main.go:16 +0x47f
api02-1  | 2024/03/07 14:54:45 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | 
mysql exited with code 0
api02-1  | goroutine 1 [running]:
api02-1  | main.main()
api02-1  | 	/app/cmd/server/main.go:16 +0x47f
api02-1  | 2024/03/07 14:54:46 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | 
api02-1  | goroutine 1 [running]:
api02-1  | main.main()
api02-1  | 	/app/cmd/server/main.go:16 +0x47f
api02-1  | 2024/03/07 14:54:48 error on ping connection: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | panic: dial tcp 192.168.0.2:3306: connect: connection refused
api02-1  | 
api02-1  | goroutine 1 [running]:
api02-1  | main.main()
api02-1  | 	/app/cmd/server/main.go:16 +0x47f
api02-1  | 2024/03/07 14:54:52 error on ping connection: dial tcp: lookup mysql on 127.0.0.11:53: server misbehaving
api02-1  | panic: dial tcp: lookup mysql on 127.0.0.11:53: server misbehaving
api02-1  | 
api02-1  | goroutine 1 [running]:
api02-1  | main.main()
api02-1  | 	/app/cmd/server/main.go:16 +0x47f
api02-1 exited with code 2
api01-1 exited with code 2
mysql    | 2024-03-07 14:54:53+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql    | 2024-03-07 14:54:53+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.44-1.el7 started.
mysql    | '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
mysql    | 2024-03-07T14:54:54.118617Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
mysql    | 2024-03-07T14:54:54.119555Z 0 [Note] mysqld (mysqld 5.7.44) starting as process 1 ...
mysql    | 2024-03-07T14:54:54.121824Z 0 [Note] InnoDB: PUNCH HOLE support available
mysql    | 2024-03-07T14:54:54.121844Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mysql    | 2024-03-07T14:54:54.121847Z 0 [Note] InnoDB: Uses event mutexes
mysql    | 2024-03-07T14:54:54.121849Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
mysql    | 2024-03-07T14:54:54.121851Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.13
mysql    | 2024-03-07T14:54:54.121852Z 0 [Note] InnoDB: Using Linux native AIO
mysql    | 2024-03-07T14:54:54.122079Z 0 [Note] InnoDB: Number of pools: 1
mysql    | 2024-03-07T14:54:54.122180Z 0 [Note] InnoDB: Using CPU crc32 instructions
mysql    | 2024-03-07T14:54:54.123284Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
mysql    | 2024-03-07T14:54:54.128393Z 0 [Note] InnoDB: Completed initialization of buffer pool
mysql    | 2024-03-07T14:54:54.129845Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mysql    | 2024-03-07T14:54:54.141479Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
mysql    | 2024-03-07T14:54:54.142527Z 0 [Note] InnoDB: Log scan progressed past the checkpoint lsn 2768732
mysql    | 2024-03-07T14:54:54.241131Z 0 [Note] InnoDB: Doing recovery: scanned up to log sequence number 8011264
mysql    | 2024-03-07T14:54:54.322643Z 0 [Note] InnoDB: Doing recovery: scanned up to log sequence number 12233540
mysql    | 2024-03-07T14:54:54.323294Z 0 [Note] InnoDB: Database was not shutdown normally!
mysql    | 2024-03-07T14:54:54.323305Z 0 [Note] InnoDB: Starting crash recovery.
mysql    | 2024-03-07T14:54:54.333908Z 0 [Note] InnoDB: Starting an apply batch of log records to the database...
mysql    | InnoDB: Progress in percent: 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 
mysql    | 2024-03-07T14:54:55.115862Z 0 [Note] InnoDB: Apply batch completed
mysql    | 2024-03-07T14:54:55.218467Z 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
mysql    | 2024-03-07T14:54:55.218487Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mysql    | 2024-03-07T14:54:55.218523Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mysql    | 2024-03-07T14:54:55.244742Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mysql    | 2024-03-07T14:54:55.245377Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
mysql    | 2024-03-07T14:54:55.245389Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
mysql    | 2024-03-07T14:54:55.246279Z 0 [Note] InnoDB: 5.7.44 started; log sequence number 12233540
mysql    | 2024-03-07T14:54:55.246888Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mysql    | 2024-03-07T14:54:55.247057Z 0 [Note] Plugin 'FEDERATED' is disabled.
mysql    | 2024-03-07T14:54:55.247745Z 0 [Note] InnoDB: Buffer pool(s) load completed at 240307 14:54:55
mysql    | 2024-03-07T14:54:55.250384Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
mysql    | 2024-03-07T14:54:55.250395Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
mysql    | 2024-03-07T14:54:55.250398Z 0 [Warning] A deprecated TLS version TLSv1 is enabled. Please use TLSv1.2 or higher.
mysql    | 2024-03-07T14:54:55.250399Z 0 [Warning] A deprecated TLS version TLSv1.1 is enabled. Please use TLSv1.2 or higher.
mysql    | 2024-03-07T14:54:55.250855Z 0 [Warning] CA certificate ca.pem is self signed.
mysql    | 2024-03-07T14:54:55.250883Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
mysql    | 2024-03-07T14:54:55.251104Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
mysql    | 2024-03-07T14:54:55.251140Z 0 [Note] IPv6 is available.
mysql    | 2024-03-07T14:54:55.251153Z 0 [Note]   - '::' resolves to '::';
mysql    | 2024-03-07T14:54:55.251171Z 0 [Note] Server socket created on IP: '::'.
mysql    | 2024-03-07T14:54:55.255606Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
mysql    | 2024-03-07T14:54:55.386084Z 0 [Note] Event Scheduler: Loaded 0 events
mysql    | 2024-03-07T14:54:55.386348Z 0 [Note] mysqld: ready for connections.
mysql    | Version: '5.7.44'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
mysql    | 2024-03-07T14:55:24.478323Z 2 [Note] Aborted connection 2 to db: 'mysql-db' user: 'root' host: '192.168.0.3' (Got an error reading communication packets)
mysql    | 2024-03-07T14:55:24.479005Z 3 [Note] Aborted connection 3 to db: 'mysql-db' user: 'root' host: '192.168.0.4' (Got an error reading communication packets)
api02-1 exited with code 0
api02-1 exited with code 2
api01-1 exited with code 0
api01-1 exited with code 2
mysql    | 2024-03-07T14:55:25.342773Z 0 [Note] Giving 0 client threads a chance to die gracefully
